### PR TITLE
Adding more Belgium apps we use

### PR DESCRIPTION
**Pull request by ruditimmermans**

### CODE REVIEW

**Comment by Roker2** [comment]
Is it okay that `aftership` app icon is so small?

**Comment by ruditimmermans** [comment]
> Is it okay that `aftership` app icon is so small?

It's 104x104 it seems so it's also small into the Play Store...

**Comment by wurzer** [comment]
Let's create a ticket for icon suggestions to forward it to our designer. I noticed that the edges, line width vary and a slight dark edge can be seen. We should recreate the icons in a graphics program, instead of putting existing icons freu.

**Comment by ruditimmermans** [comment]
Ok sounds good thanks!

**Comment by ruditimmermans** [comment]
Hi Dr. Wurzur, would this mean the icons would never come into the Launcher ?

**Comment by wurzer** [comment]
Let's make a list of relevanticons and our designer can create them The graphics must be created as a line drawing in a vector graphics format. Ensure consistent line width, margin spacing and scaling of the PNG export. If we take existing icons, free them and change the color, the white strokes will have fine dark borders and the stroke width will not be consistent. Therefore my suggestion is to collect the apps for which a sopecial icon is worthwhile because they are popular.

**Comment by ruditimmermans** [comment]
OK i make a list with the apps as most of us here use daily ok ?

**Pull request closed without merging**
