### PR TITLE
android: Use shortEdges for CutoutMode

### PR DESCRIPTION
**Pull request by erfanoabdi**
* Fix fullscreen mode for devices with cutout

### CODE REVIEW

**Comment by wurzer** [comment]
The issue with a black bar at the top does only occur in the full screen mode of the launcher. To enable fullscreen I just use `appwindow.visibility = 5`. Do you think that modifying the manifest could fix it?

**Comment by erfanoabdi** [comment]
`visibility = 5` is correct for fullscreen
just on devices with defined cutout layout `android:windowLayoutInDisplayCutoutMode` can have 3 possible option: 
default, shortEdges, never  
with default it makes big black bar, but `shortEdges` is what we needed 
Screenshot_20210715-145620_Volla vs Screenshot_20210715-145413_Volla

**Comment by wurzer** [comment]
Would this replace the layoutAction in the LayoutUtil.class?

**Comment by erfanoabdi** [comment]
i'm not sure how layoutAction in LayoutUtil.class works, but i guess doesn't replace anything there

**Pull request merged**
